apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ip-app
  labels:
    app: go-ip-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-ip-app
  template:
    metadata:
      labels:
        app: go-ip-app
    spec:
      containers:
      - name: go-ip-app
        image: gcr.io/idv-dev-0/go-ip-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-ip-app-service
  labels:
    app: go-ip-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-ip-app